'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const root=__dirname,publicRoot=path.join(root,'public'),{products}=require('./catalog'),{products:regularProducts}=require('./legacy-catalog'),{delivery,OFFER_DEADLINE}=require('./shop-config'),{customerTemplate,ownerTemplate}=require('./email');
assert.equal(products.length,292);assert.equal(new Set(products.map(p=>p.id)).size,292);assert(regularProducts.length>300);assert.equal(OFFER_DEADLINE,'2026-12-31T23:59:59+02:00');
assert.equal(delivery.quote('collection-george').customerChargeCents,0);assert.equal(delivery.quote('george').customerChargeCents,7900);assert.equal(delivery.quote('wilderness').customerChargeCents,9900);assert.equal(delivery.quote('knysna').customerChargeCents,15900);assert.throws(()=>delivery.quote('cape-town'));
const order={order_number:'EPB-20261005-0123456789ABCDEF',order_type:'bogo',customer:{firstName:'Test',lastName:'Customer',email:'test@example.com',phone:'0771234567'},items:[{productId:164,reference:'Black Opium',variant:'Elysean Impression',quantity:1,lineTotalCents:38400}],delivery:{areaName:'George and immediate suburbs',zoneName:'Zone 1 — George local delivery',method:'local_delivery',addressLine1:'1 Main Road',suburb:'George',postalCode:'6529',instructions:'Gate 2',schedule:'Weekday delivery after 17:00. No Sunday delivery.'},delivery_zone:'ZONE_1',subtotal_cents:38400,shipping_cents:7900,total_cents:46300,checkout_id:'checkout_test',payment_id:'payment_test'};
for(const html of [customerTemplate(order),ownerTemplate(order)]){assert.match(html,/EPB-20261005/);assert.match(html,/George/);assert(!/PUDO|locker/i.test(html));}
const tracking=fs.readFileSync(path.join(publicRoot,'tracking.js'),'utf8');assert(tracking.includes("'1084792373896315'"));assert(tracking.includes("'1723955528897231'"));assert(tracking.includes("const GA = 'G-NT5SEGTN2N'"));
for(const file of ['promo.html','bogo-checkout.html','bogo-success.html','stock-admin.html','checkout.html','samples.html']){const html=fs.readFileSync(path.join(publicRoot,file),'utf8');for(const match of html.matchAll(/(?:src|href)="([^"?#]+)(?:[?#][^"]*)?"/g)){const target=match[1];if(/^(?:https?:|mailto:|tel:|#)/.test(target))continue;assert(fs.existsSync(path.join(publicRoot,target.replace(/^\//,''))),`${file}: missing ${target}`);}}
for(const file of ['index.js','db.js','email.js','catalog.js','legacy-catalog.js','shop-config.js','public/delivery-config.js','public/app.js','public/bogo-checkout.js','public/bogo-success.js','public/checkout.js','public/samples.js','public/tracking.js'])execFileSync(process.execPath,['--check',path.join(root,file)],{stdio:'pipe'});
for(const file of fs.readdirSync(publicRoot)){if(!/\.(?:html|js|css)$/.test(file))continue;const content=fs.readFileSync(path.join(publicRoot,file),'utf8');assert(!/PUDO|selected locker/i.test(content),`${file} contains retired delivery wording`);assert(!content.includes('27648570979'));}
const secret=crypto.randomBytes(32);process.env.YOCO_WEBHOOK_SECRET=`whsec_${secret.toString('base64')}`;const {verifyWebhookSignature,customerFrom,deliveryFrom}=require('./index'),timestamp=String(Math.floor(Date.now()/1000)),id='evt_test',body=JSON.stringify({id,type:'payment.succeeded'}),sig=crypto.createHmac('sha256',secret).update(`${id}.${timestamp}.${body}`).digest('base64');assert(verifyWebhookSignature(id,timestamp,body,`v1,${sig}`));assert.equal(customerFrom({firstName:'A',lastName:'B',email:'a@example.com',phone:'077 123 4567'}).email,'a@example.com');assert.equal(deliveryFrom({areaId:'george',addressLine1:'1 Main',suburb:'George',postalCode:'6529'}).zoneCode,'ZONE_1');assert.throws(()=>deliveryFrom({areaId:'knysna'}));
console.log('PASS: catalogues, local delivery zones, emails, assets, tracking, syntax, validation and Yoco signature.');
